# Generated by Django 3.0.2 on 2020-01-31 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.TextField()),
                ('kr_name', models.TextField()),
                ('operating_hours', models.TextField()),
                ('hours_breakfast', models.TextField()),
                ('hours_lunch', models.TextField()),
                ('hours_dinner', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.TextField()),
                ('kr_name', models.TextField()),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(blank=True, choices=[('BR', 'breakfast'), ('LU', 'lunch'), ('DN', 'dinner')], max_length=2)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Restaurant')),
            ],
        ),
    ]
